import jsonToLua from "json-to-lua";
import fetchLoRData from "./src/FetchLoRData.js";
import { parseLorData } from "./src/ParseLoRData.js";
import writeLuaFile from "./src/WriteLua.js";

(async () => {
  const patchVersion = "5.4";
  const setNumber = 9;
  let a = await fetchLoRData(setNumber);
  let parsed = parseLorData(a);
  let luaObject = {};
  for(let card of parsed) {
    let { id, ...rest } = card;
    luaObject[id] = rest;
  }
  let luaFile = jsonToLua(luaObject, { omitFalsies: true });
  luaFile = `
-- Generated by LoRProcessor
-- Patch: ${patchVersion}
-- Set: ${setNumber}
-- <pre>
return {
${luaFile}
}
-- </pre>
-- [[Category:Lua]]`;
  writeLuaFile("Set9_V5.4", luaFile);
})();